---
default: &default
  bugsnag_key: <%= String(ENV['BUGSNAG_API_KEY']) || '' %>
  services:
    mpay:
      url: <%= String(ENV['MPAY_URL']) || 'https://www.mpay.com' %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
