default: &default
  adapter: postgresql
  encoding: unicode
  username:        <%= String(ENV['DB_USER'] || 'ruby') %>
  password:        <%= String(ENV['DB_PASSWORD'] || 'ruby') %>
  host:            <%= String(ENV['DB_HOST'] || 'localhost') %>
  max_connections: <%= Integer(ENV['PUMA_MAX_THREADS'] || 10) %>

development:
  <<: *default
  database: <%= String(ENV['DB_NAME'] || 'ps_mpay_dev') %>

test:
  <<: *default
  database: <%= String(ENV['DB_NAME'] || 'ps_mpay_test') %>

production:
  <<: *default
  database: <%= String(ENV['DB_NAME']) %>
